name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKERHUB_USERNAME: flcdrg
  REGISTRY: ghcr.io
  REGISTRY2: docker.io
  DOCKERHUB_REPO: flcdrg/${{ github.repository }}
  GHCR_REPO: ghcr.io/flcdrg/${{ github.repository }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to update tags
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Dump environment
        run: env -0 | sort -z | tr '\0' '\n'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY2 }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY2 }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=schedule
            type=semver,pattern={{version}},value=${{ steps.tag_version.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag_version.outputs.new_tag }}
            type=semver,pattern={{major}},value=${{ steps.tag_version.outputs.new_tag }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          flavor: |
            latest=true

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.18.0
        with:
          # platforms: ${{ matrix.platform }}
          # context: src
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # load: true # Make image available locally
          outputs: type=image,"name=${{ env.DOCKERHUB_REPO }}",name-canonical=true,push=true
